km = float(input("Enter car mileage : "))
f = open('thetas', 'r')
lines = f.read().split('\n')
f.close()
t0 = float(lines[0])
t1 = float(lines[1])
pe = t0 + (t1 * km)
pe = max(0, pe)
print("Estimated price : " + str(pe))