km = float(input("Entrez le kilometrage : "))
print(km)
f = open('thetas', 'r')
lines = f.read().split('\n')
f.close()
t0 = float(lines[0])
t1 = float(lines[1])
pe = t0 + (t1 * km)
print("Prix estimé : " + str(pe))